name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  publish_docker_hub:
    name: Publish image to Docker Hub
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/interactive-employee-classifier:latest
  render_deployment:
    needs: [publish_docker_hub]
    runs-on: ubuntu-22.04
    environment: production
    steps:
      - name: Trigger Render deployment
        if: ${{ github.event_name == 'push' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
